/*
 * AVACloud API 1.29.0
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.danglit.avacloud.client.api;

import com.danglit.avacloud.client.models.ApiError;
import java.io.File;
import com.danglit.avacloud.client.models.ProjectDto;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GaebConversionApi
 */
@Ignore
public class GaebConversionApiTest {

    private final GaebConversionApi api = new GaebConversionApi();

    
    /**
     * Converts GAEB files to Dangl.AVA projects
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void gaebConversionConvertToAvaTest() throws Exception {
        File gaebFile = null;
        Boolean supportSkippedItemNumberLevelsInPositions = null;
        Boolean removePlainTextLongTexts = null;
        Boolean removeHtmlLongTexts = null;
        ProjectDto response = api.gaebConversionConvertToAva(gaebFile, supportSkippedItemNumberLevelsInPositions, removePlainTextLongTexts, removeHtmlLongTexts);

        // TODO: test validations
    }
    
    /**
     * Converts GAEB files to Excel
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void gaebConversionConvertToExcelTest() throws Exception {
        File gaebFile = null;
        Boolean supportSkippedItemNumberLevelsInPositions = null;
        Boolean writePrices = null;
        Boolean writeLongTexts = null;
        String conversionCulture = null;
        File response = api.gaebConversionConvertToExcel(gaebFile, supportSkippedItemNumberLevelsInPositions, writePrices, writeLongTexts, conversionCulture);

        // TODO: test validations
    }
    
    /**
     * Converts GAEB files to GAEB files. Used for example when transforming or repairing GAEB files.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void gaebConversionConvertToGaebTest() throws Exception {
        File gaebFile = null;
        Boolean supportSkippedItemNumberLevelsInPositions = null;
        String destinationGaebType = null;
        String targetExchangePhaseTransform = null;
        Boolean enforceStrictOfferPhaseLongTextOutput = null;
        Boolean exportQuantityDetermination = null;
        Boolean removeUnprintableCharactersFromTexts = null;
        File response = api.gaebConversionConvertToGaeb(gaebFile, supportSkippedItemNumberLevelsInPositions, destinationGaebType, targetExchangePhaseTransform, enforceStrictOfferPhaseLongTextOutput, exportQuantityDetermination, removeUnprintableCharactersFromTexts);

        // TODO: test validations
    }
    
    /**
     * Converts GAEB files to Oenorm files
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void gaebConversionConvertToOenormTest() throws Exception {
        File gaebFile = null;
        Boolean supportSkippedItemNumberLevelsInPositions = null;
        String destinationOenormType = null;
        Boolean tryRepairProjectStructure = null;
        Boolean skipTryEnforceSchemaCompliantXmlOutput = null;
        Boolean removeUnprintableCharactersFromTexts = null;
        File response = api.gaebConversionConvertToOenorm(gaebFile, supportSkippedItemNumberLevelsInPositions, destinationOenormType, tryRepairProjectStructure, skipTryEnforceSchemaCompliantXmlOutput, removeUnprintableCharactersFromTexts);

        // TODO: test validations
    }
    
}
