/*
 * AVACloud API 1.41.0
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.41.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.danglit.avacloud.client.models;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Represents valid REB target types
 */
@JsonAdapter(DestinationRebType.Adapter.class)
public enum DestinationRebType {
  
  D11("D11"),
  
  X31GAEBXMLV32("X31GaebXmlV32"),
  
  X31GAEBXMLV33("X31GaebXmlV33");

  private String value;

  DestinationRebType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DestinationRebType fromValue(String text) {
    for (DestinationRebType b : DestinationRebType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<DestinationRebType> {
    @Override
    public void write(final JsonWriter jsonWriter, final DestinationRebType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DestinationRebType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DestinationRebType.fromValue(String.valueOf(value));
    }
  }
}

