/*
 * AVACloud API 1.59.0
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.59.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.danglit.avacloud.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ForgotPasswordPost
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-04-09T18:36:39.750Z")
public class ForgotPasswordPost {
  @SerializedName("identifier")
  private String identifier = null;

  @SerializedName("preferredLanguages")
  private List<String> preferredLanguages = null;

  @SerializedName("serviceLoginRedirectUri")
  private String serviceLoginRedirectUri = null;

  public ForgotPasswordPost identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * Get identifier
   * @return identifier
  **/
  @ApiModelProperty(required = true, value = "")
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public ForgotPasswordPost preferredLanguages(List<String> preferredLanguages) {
    this.preferredLanguages = preferredLanguages;
    return this;
  }

  public ForgotPasswordPost addPreferredLanguagesItem(String preferredLanguagesItem) {
    if (this.preferredLanguages == null) {
      this.preferredLanguages = new ArrayList<>();
    }
    this.preferredLanguages.add(preferredLanguagesItem);
    return this;
  }

   /**
   * Get preferredLanguages
   * @return preferredLanguages
  **/
  @ApiModelProperty(value = "")
  public List<String> getPreferredLanguages() {
    return preferredLanguages;
  }

  public void setPreferredLanguages(List<String> preferredLanguages) {
    this.preferredLanguages = preferredLanguages;
  }

  public ForgotPasswordPost serviceLoginRedirectUri(String serviceLoginRedirectUri) {
    this.serviceLoginRedirectUri = serviceLoginRedirectUri;
    return this;
  }

   /**
   * Get serviceLoginRedirectUri
   * @return serviceLoginRedirectUri
  **/
  @ApiModelProperty(value = "")
  public String getServiceLoginRedirectUri() {
    return serviceLoginRedirectUri;
  }

  public void setServiceLoginRedirectUri(String serviceLoginRedirectUri) {
    this.serviceLoginRedirectUri = serviceLoginRedirectUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForgotPasswordPost forgotPasswordPost = (ForgotPasswordPost) o;
    return Objects.equals(this.identifier, forgotPasswordPost.identifier) &&
        Objects.equals(this.preferredLanguages, forgotPasswordPost.preferredLanguages) &&
        Objects.equals(this.serviceLoginRedirectUri, forgotPasswordPost.serviceLoginRedirectUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, preferredLanguages, serviceLoginRedirectUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForgotPasswordPost {\n");
    
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    preferredLanguages: ").append(toIndentedString(preferredLanguages)).append("\n");
    sb.append("    serviceLoginRedirectUri: ").append(toIndentedString(serviceLoginRedirectUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

