/*
 * AVACloud API 1.55.0
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.55.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.danglit.avacloud.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.danglit.avacloud.client.models.LineItemAttribute;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Information about a single line item
 */
@ApiModel(description = "Information about a single line item")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-02-11T12:55:14.413Z")
public class LineItemInformation {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("sellerIdentifier")
  private String sellerIdentifier = null;

  @SerializedName("buyerIdentifier")
  private String buyerIdentifier = null;

  @SerializedName("standardIdentifier")
  private String standardIdentifier = null;

  @SerializedName("standardSchemeId")
  private String standardSchemeId = null;

  @SerializedName("classificationIdentifiers")
  private List<String> classificationIdentifiers = null;

  @SerializedName("countryOfOrigin")
  private String countryOfOrigin = null;

  @SerializedName("attributes")
  private List<LineItemAttribute> attributes = null;

  public LineItemInformation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A name for the line item
   * @return name
  **/
  @ApiModelProperty(value = "A name for the line item")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LineItemInformation description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A description for the line item
   * @return description
  **/
  @ApiModelProperty(value = "A description for the line item")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public LineItemInformation sellerIdentifier(String sellerIdentifier) {
    this.sellerIdentifier = sellerIdentifier;
    return this;
  }

   /**
   * An identifier assigned by the seller, e.g. an internal article number
   * @return sellerIdentifier
  **/
  @ApiModelProperty(value = "An identifier assigned by the seller, e.g. an internal article number")
  public String getSellerIdentifier() {
    return sellerIdentifier;
  }

  public void setSellerIdentifier(String sellerIdentifier) {
    this.sellerIdentifier = sellerIdentifier;
  }

  public LineItemInformation buyerIdentifier(String buyerIdentifier) {
    this.buyerIdentifier = buyerIdentifier;
    return this;
  }

   /**
   * An identifier assigned by the buyer, e.g. an internal article number
   * @return buyerIdentifier
  **/
  @ApiModelProperty(value = "An identifier assigned by the buyer, e.g. an internal article number")
  public String getBuyerIdentifier() {
    return buyerIdentifier;
  }

  public void setBuyerIdentifier(String buyerIdentifier) {
    this.buyerIdentifier = buyerIdentifier;
  }

  public LineItemInformation standardIdentifier(String standardIdentifier) {
    this.standardIdentifier = standardIdentifier;
    return this;
  }

   /**
   * A standard identifier for the line item, e.g. an EAN or a GTIN
   * @return standardIdentifier
  **/
  @ApiModelProperty(value = "A standard identifier for the line item, e.g. an EAN or a GTIN")
  public String getStandardIdentifier() {
    return standardIdentifier;
  }

  public void setStandardIdentifier(String standardIdentifier) {
    this.standardIdentifier = standardIdentifier;
  }

  public LineItemInformation standardSchemeId(String standardSchemeId) {
    this.standardSchemeId = standardSchemeId;
    return this;
  }

   /**
   * If used together with StandardIdentifier, this is the scheme identifier for which standard is used.
   * @return standardSchemeId
  **/
  @ApiModelProperty(value = "If used together with StandardIdentifier, this is the scheme identifier for which standard is used.")
  public String getStandardSchemeId() {
    return standardSchemeId;
  }

  public void setStandardSchemeId(String standardSchemeId) {
    this.standardSchemeId = standardSchemeId;
  }

  public LineItemInformation classificationIdentifiers(List<String> classificationIdentifiers) {
    this.classificationIdentifiers = classificationIdentifiers;
    return this;
  }

  public LineItemInformation addClassificationIdentifiersItem(String classificationIdentifiersItem) {
    if (this.classificationIdentifiers == null) {
      this.classificationIdentifiers = new ArrayList<>();
    }
    this.classificationIdentifiers.add(classificationIdentifiersItem);
    return this;
  }

   /**
   * A list of classification identifiers for the line item
   * @return classificationIdentifiers
  **/
  @ApiModelProperty(value = "A list of classification identifiers for the line item")
  public List<String> getClassificationIdentifiers() {
    return classificationIdentifiers;
  }

  public void setClassificationIdentifiers(List<String> classificationIdentifiers) {
    this.classificationIdentifiers = classificationIdentifiers;
  }

  public LineItemInformation countryOfOrigin(String countryOfOrigin) {
    this.countryOfOrigin = countryOfOrigin;
    return this;
  }

   /**
   * The origin country code according to ISO 3166-1 in 2 letter format
   * @return countryOfOrigin
  **/
  @ApiModelProperty(value = "The origin country code according to ISO 3166-1 in 2 letter format")
  public String getCountryOfOrigin() {
    return countryOfOrigin;
  }

  public void setCountryOfOrigin(String countryOfOrigin) {
    this.countryOfOrigin = countryOfOrigin;
  }

  public LineItemInformation attributes(List<LineItemAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public LineItemInformation addAttributesItem(LineItemAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Optional additional attributes for this line item
   * @return attributes
  **/
  @ApiModelProperty(value = "Optional additional attributes for this line item")
  public List<LineItemAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<LineItemAttribute> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineItemInformation lineItemInformation = (LineItemInformation) o;
    return Objects.equals(this.name, lineItemInformation.name) &&
        Objects.equals(this.description, lineItemInformation.description) &&
        Objects.equals(this.sellerIdentifier, lineItemInformation.sellerIdentifier) &&
        Objects.equals(this.buyerIdentifier, lineItemInformation.buyerIdentifier) &&
        Objects.equals(this.standardIdentifier, lineItemInformation.standardIdentifier) &&
        Objects.equals(this.standardSchemeId, lineItemInformation.standardSchemeId) &&
        Objects.equals(this.classificationIdentifiers, lineItemInformation.classificationIdentifiers) &&
        Objects.equals(this.countryOfOrigin, lineItemInformation.countryOfOrigin) &&
        Objects.equals(this.attributes, lineItemInformation.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, sellerIdentifier, buyerIdentifier, standardIdentifier, standardSchemeId, classificationIdentifiers, countryOfOrigin, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineItemInformation {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    sellerIdentifier: ").append(toIndentedString(sellerIdentifier)).append("\n");
    sb.append("    buyerIdentifier: ").append(toIndentedString(buyerIdentifier)).append("\n");
    sb.append("    standardIdentifier: ").append(toIndentedString(standardIdentifier)).append("\n");
    sb.append("    standardSchemeId: ").append(toIndentedString(standardSchemeId)).append("\n");
    sb.append("    classificationIdentifiers: ").append(toIndentedString(classificationIdentifiers)).append("\n");
    sb.append("    countryOfOrigin: ").append(toIndentedString(countryOfOrigin)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

