/*
 * AVACloud API 1.59.0
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.59.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.danglit.avacloud.client.models;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * This enum represents the different ways in which a complementing position type can be specified. It is typically only used in GAEB exports, since in Dangl.AVA, complementing positions are always explicitly referenced.
 */
@JsonAdapter(PositionComplementingTypeDto.Adapter.class)
public enum PositionComplementingTypeDto {
  
  UNDEFINED("Undefined"),
  
  ALLPREVIOUSMARKEDPOSITIONS("AllPreviousMarkedPositions"),
  
  ALLPREVIOUSPOSITIONS("AllPreviousPositions"),
  
  REFERENCEDPOSITIONS("ReferencedPositions");

  private String value;

  PositionComplementingTypeDto(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PositionComplementingTypeDto fromValue(String text) {
    for (PositionComplementingTypeDto b : PositionComplementingTypeDto.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PositionComplementingTypeDto> {
    @Override
    public void write(final JsonWriter jsonWriter, final PositionComplementingTypeDto enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PositionComplementingTypeDto read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PositionComplementingTypeDto.fromValue(String.valueOf(value));
    }
  }
}

