/*
 * AVACloud API 1.29.0
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.danglit.avacloud.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.danglit.avacloud.client.models.DurationUnitDto;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * This class does not represent a typical &#x60;TimeSpan&#x60; but has a scalar value int Duration and a DurationUnit Unit to represent durations as typically used in contracts, e.g. 5 Months
 */
@ApiModel(description = "This class does not represent a typical `TimeSpan` but has a scalar value int Duration and a DurationUnit Unit to represent durations as typically used in contracts, e.g. 5 Months")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-27T14:07:49.059Z")
public class WarrantyDurationDto {
  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("unit")
  private DurationUnitDto unit = null;

  public WarrantyDurationDto duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * The scalar value of the duration. This value must be equal to or bigger than zero (&gt;&#x3D; 0). Negative values can not be set and will be ignored.
   * @return duration
  **/
  @ApiModelProperty(required = true, value = "The scalar value of the duration. This value must be equal to or bigger than zero (>= 0). Negative values can not be set and will be ignored.")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public WarrantyDurationDto unit(DurationUnitDto unit) {
    this.unit = unit;
    return this;
  }

   /**
   * The unit of the duration
   * @return unit
  **/
  @ApiModelProperty(required = true, value = "The unit of the duration")
  public DurationUnitDto getUnit() {
    return unit;
  }

  public void setUnit(DurationUnitDto unit) {
    this.unit = unit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WarrantyDurationDto warrantyDurationDto = (WarrantyDurationDto) o;
    return Objects.equals(this.duration, warrantyDurationDto.duration) &&
        Objects.equals(this.unit, warrantyDurationDto.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, unit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WarrantyDurationDto {\n");
    
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

